### ISSUE TITLE
Command doesn't work

### ISSUE THREAD

**Issue by ElCanadian** [itschip/react-fivem-lua-boilerplate#2]
Hi, I'm trying to get this boilerplate running on my FiveM server but when I do the /show:nui command, nothing happens. Even after I put a test text on the App.tsx and build it after.

Any clues?

Thanks in advance, and your project seems to be insanely helpful for further projects 👍

**Comment by itschip** [comment]
I will check it out today :)

**Comment by itschip** [comment]
Should be fixed now :)

**Comment by ElCanadian** [comment]
Thanks 👍
